### ISSUE TITLE
More than one unit

### ISSUE THREAD

**Issue by zajabbar1** [chrizzzzz/LEDDisplay74HC595#2]
Is it possible to use more than one unit at the same time. I mean the same wire and address.

Thank you and best regards
zajabbar99@gmail. Com

**Comment by chrizzzzz** [comment]
Hi zajabbar1!

I think you can connect the unit I have with more units in serial. But this library only supports one unit with 4 digits.

Best Regards,
chrizzzzz

**Comment by zajabbar1** [comment]
Thank you for your kind reply. Could you please help me by giving example.

Thank you and best regards
Zuhair

**Comment by chrizzzzz** [comment]
No problem.

Check out this topic: https://forum.arduino.cc/index.php?topic=371221.0

I haven't tried it, but after daisy chaining the devices as described in the topic, it seems like you should shift out the digit on the same position twice, one for each display, before you latch the reset clock with a LOW and HIGH.

Fell free to fork this library and add the functionality. If I get the time I might do it as well. :-)

Best Regards,
chrizzzzz

**Comment by zajabbar1** [comment]
Dear Mr.chrizzzzz,

Thank you very much. It's working very well.

Best regards
Zuhair
